# Generated by Django 2.1.7 on 2019-03-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('CI', models.CharField(max_length=8)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Teléfono', models.CharField(max_length=8)),
                ('Celular', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('Padrón', models.CharField(max_length=50)),
                ('Torre', models.CharField(max_length=6)),
                ('Apartamento', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Referencia', models.CharField(max_length=10)),
                ('Estaciona_vehículo', models.CharField(max_length=2)),
                ('Matrícula', models.CharField(max_length=20)),
            ],
        ),
    ]
